export const NAME_MIN_LENGTH = 3;
export const NAME_MAX_LENGTH = 45;

export const USERNAME_MIN_LENGTH = 4;
export const USERNAME_MAX_LENGTH = 24;

export const PASSWORD_MIN_LENGTH = 6;

export const STORE_NAME_MIN_LENGTH = USERNAME_MIN_LENGTH;
export const STORE_NAME_MAX_LENGTH = USERNAME_MAX_LENGTH;
